=== authzforce/java-xacml-sdk/interface/soap/src/main/java/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://sunxacml.sourceforge.net/schema/config-0.3"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:config="http://sunxacml.sourceforge.net/schema/config-0.3"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:element name="config">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="pdp" type="config:PDPType" />
				<xsd:element name="attributeFactory" type="config:AttributeFactoryType" />
				<xsd:element name="combiningAlgFactory" type="config:CombiningFactoryType" />
				<xsd:element name="functionFactory" type="config:FunctionFactoryType" />				
			</xsd:choice>
			<xsd:attribute name="defaultPDP" type="xsd:string" use="required" />
			<xsd:attribute name="defaultAttributeFactory" type="xsd:string"
				use="required" />
			<xsd:attribute name="defaultCombiningAlgFactory" type="xsd:string"
				use="required" />
			<xsd:attribute name="defaultFunctionFactory" type="xsd:string"
				use="required" />				
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="PDPType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="attributeFinderModule" type="config:AttributeFinderType" />
			<xsd:element name="resourceFinderModule" type="config:ClassType" />
			<xsd:element name="policyFinderModule" type="config:ClassType" />
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="AttributeFactoryType">
		<xsd:sequence>
			<xsd:element name="datatype" type="config:IdentifiedType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="useStandardDatatypes" type="xsd:boolean"
			use="optional" default="true" />
	</xsd:complexType>

	<xsd:complexType name="CombiningFactoryType">
		<xsd:sequence>
			<xsd:element name="algorithm" type="config:ClassType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="useStandardAlgorithms" type="xsd:boolean"
			use="optional" default="true" />
	</xsd:complexType>

	<xsd:complexType name="FunctionFactoryType">
		<xsd:sequence>
			<xsd:element name="target" type="config:FunctionCollectionType"
				minOccurs="0" />
			<xsd:element name="condition" type="config:FunctionCollectionType"
				minOccurs="0" />
			<xsd:element name="general" type="config:FunctionCollectionType"
				minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="useStandardFunctions" type="xsd:boolean"
			use="optional" default="true" />
	</xsd:complexType>

	<xsd:complexType name="FunctionCollectionType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="function" type="config:ClassType" />
			<xsd:element name="abstractFunction" type="config:IdentifiedType" />
			<xsd:element name="functionCluster" type="config:ClassType" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="IdentifiedType" mixed="true">
		<xsd:complexContent mixed="true">
			<xsd:extension base="config:ClassType">
				<xsd:attribute name="identifier" type="xsd:anyURI"
					use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ClassType" mixed="true">
		<xsd:complexContent mixed="true">
			<xsd:extension base="config:ClassParametersType">
				<xsd:attribute name="class" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="AttributeFinderType" mixed="true">
		<xsd:complexContent mixed="true">
			<xsd:extension base="config:ClassParametersType">
				<xsd:sequence>
					<xsd:element name="Option" type="config:OptionType"
						maxOccurs="unbounded" minOccurs="0">
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="class" type="xsd:string" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="OptionType">
		<xsd:complexContent mixed="true">
			<xsd:extension base="config:ClassParametersType">
				<xsd:sequence>
					<xsd:element name="url" type="xsd:string" minOccurs="1" />
					<xsd:element name="username" type="xsd:string" minOccurs="0" />
					<xsd:element name="password" type="xsd:string" minOccurs="0" />		
					<xsd:element name="dbName" type="xsd:string" minOccurs="0" />
					<xsd:element name="driver" type="xsd:string" minOccurs="0" />				
					<xsd:element name="attributeSupportedId" type="xsd:string" minOccurs="1" />
					<xsd:element name="sqlRequest" type="xsd:string" minOccurs="0" />					
					<xsd:element name="fortressAttribute" type="xsd:string" minOccurs="0" />
					<xsd:element name="substituteValue" type="xsd:string" minOccurs="1" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ClassParametersType" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="string" type="xsd:string" />
			<xsd:element name="list" type="config:ClassParametersType" />
			<xsd:element name="Options" type="config:OptionType" />
		</xsd:choice>
	</xsd:complexType>

</xsd:schema>

=== authzforce/java-xacml-sdk/interface/rest/src/test/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://authzforce.thalesgroup.com/schema" defaultPDP="AuthZForce-REST"
	defaultAttributeFactory="attr" defaultCombiningAlgFactory="comb"
	defaultFunctionFactory="func"
	xsi:schemaLocation="http://authzforce.thalesgroup.com/schema config.xsd">
	<pdp name="AuthZForce-REST">
<!-- 	<attributeFinderModule class="com.sun.xacml.finder.impl.AttributeRoleFinder"> -->
<!-- 		<Options>			 -->
<!-- 			<url>http://localhost:8080/FortressWS/FortressWS</url> -->
<!-- 			<attributeSupportedId>fortress-role</attributeSupportedId> -->
<!-- 			<fortressAttribute>Session</fortressAttribute> -->
<!-- 			<substituteValue>urn:oasis:names:tc:xacml:1.0:subject:subject-id</substituteValue> -->
<!-- 		</Options> -->
<!-- 	</attributeFinderModule> -->
		<attributeFinderModule class="com.sun.xacml.finder.impl.AttributeDBFinder">		
			<AttributeDbFinder>
				<url>jdbc:mysql://10.222.148.101:3306/</url>
				<username>root</username>
				<password>password</password>		
				<!-- <Options> -->						
				<dbName>keystone-essex-4</dbName>
				<driver>com.mysql.jdbc.Driver</driver>
				<attributeSupportedId>tenantMember</attributeSupportedId>
				<sqlRequest>SELECT u.name as $alias FROM user_tenant_membership utm, tenant t, user u WHERE utm.tenant_id = t.id AND u.id = utm.user_id AND t.name = $filter</sqlRequest>
				<substituteValue>urn:oasis:names:tc:xacml:1.0:resource:resource-id</substituteValue>
				<!-- </Options> -->
			</AttributeDbFinder>
		</attributeFinderModule>
		<attributeFinderModule class="com.sun.xacml.finder.impl.SelectorModule" />
		<policyFinderModule class="com.sun.xacml.finder.impl.FilePolicyModule">
			<list>
				<string>src/test/resources/AuthZForce-Policy.xml</string>
			</list>
		</policyFinderModule>
	</pdp>
	<attributeFactory name="attr" useStandardDatatypes="true" />
	<combiningAlgFactory name="comb"
		useStandardAlgorithms="true" />
	<functionFactory name="func" useStandardFunctions="true">
		<!-- <condition> <function class="TimeInRangeFunction"/> </condition> -->
	</functionFactory>
</config>

=== authzforce/java-xacml-sdk/interface/soap/src/main/java/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://sunxacml.sourceforge.net/schema/config-0.3" defaultPDP="AuthZForceMvn"
	defaultAttributeFactory="attr" defaultCombiningAlgFactory="comb"
	defaultFunctionFactory="func"
	xsi:schemaLocation="http://sunxacml.sourceforge.net/schema/config-0.3 config.xsd">
	<pdp name="AuthZForceMvn">
<!-- 	<attributeFinderModule class="com.sun.xacml.finder.impl.AttributeRoleFinder"> -->
<!-- 		<Options>			 -->
<!-- 			<url>http://localhost:8080/FortressWS/FortressWS</url> -->
<!-- 			<attributeSupportedId>fortress-role</attributeSupportedId> -->
<!-- 			<fortressAttribute>Session</fortressAttribute> -->
<!-- 			<substituteValue>urn:oasis:names:tc:xacml:1.0:subject:subject-id</substituteValue> -->
<!-- 		</Options> -->
<!-- 	</attributeFinderModule> -->
		<!--  <attributeFinderModule class="com.sun.xacml.finder.impl.AttributeDBFinder">
			<Options>
				<url>jdbc:mysql://10.222.148.101:3306/</url>
				<username>root</username>
				<password>password</password>
				<dbName>keystone-essex-4</dbName>
				<driver>com.mysql.jdbc.Driver</driver>
				<attributeSupportedId>tenantMember</attributeSupportedId>
				<sqlRequest>SELECT u.name as $alias FROM user_tenant_membership utm, tenant t, user u WHERE utm.tenant_id = t.id AND u.id = utm.user_id AND t.name = $filter</sqlRequest>
				<substituteValue>urn:oasis:names:tc:xacml:1.0:resource:resource-id</substituteValue>
			</Options>
		</attributeFinderModule>-->
		<attributeFinderModule class="com.sun.xacml.finder.impl.SelectorModule" />
		<policyFinderModule class="com.sun.xacml.finder.impl.FilePolicyModule">
			<list>
				<string>/opt/AuthZForce/Policy/AuthZForce-Policy.xml</string>
			</list>
		</policyFinderModule>
	</pdp>
	<attributeFactory name="attr" useStandardDatatypes="true" />
	<combiningAlgFactory name="comb"
		useStandardAlgorithms="true" />
	<functionFactory name="func" useStandardFunctions="true">
		<!-- <condition> <function class="TimeInRangeFunction"/> </condition> -->
	</functionFactory>
</config>
